### ISSUE TITLE
Recoomendations from The Cupids

### ISSUE THREAD

**Issue by pbkabali** [Blaise-Shyaka/Tic-tac-toe#3]
Great work already @Blaise-Shyaka. 
A few reminders as you continue to build:
- [x] Remember to get user input from the `main.rb` file only
- [x] Taking user names will require some validations implementation
- [x] Labelling the board with numbers instead of letters may make the logic simpler

**Comment by Miguelus373** [comment]
- [ ] Close previous issues
- [ ] Consider changing the atrr_accesor to atrr_reader where possible
- [ ] Please show the last move in the board
